package cz.fi.muni.pa165.entity;

import cz.fi.muni.pa165.enums.Color;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

@Entity
@Table(name = "ESHOP_PRODUCTS")
public class Product {
    // * id - autogenerated @Id using IDENTITY column
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id;

    // * name - nonnullable, unique
    @NotNull
    @Column(nullable=false,unique=true)
    private String name;

    // * color - you will have to create new ENUM for this
    private Color color;

    // * java.util.Date addedDate - this field should contain only date in the database. Use @Temporal annotation
    @Temporal(TemporalType.DATE)
    private java.util.Date addedDate;

    public void setId(Long id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setColor(Color color) {
        this.color = color;
    }

    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

    public String getName() {
        return name;
    }

    public Color getColor() {
        return color;
    }

    public Date getAddedDate() {
        return addedDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !(o instanceof Product)) return false;

        Product product = (Product) o;

        return this.getName().equals(product.getName());
    }

    @Override
    public int hashCode() {
        return this.getName().hashCode();
    }
}
